services:
  proxy:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=umar.jere@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
      - "80:80"
    volumes:
      - "$PWD/STORAGE/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - frontnet  
  auth:
    build: ./auth
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/api/v1/auth/`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls.certresolver=myresolver"
    environment:
      APP_PORT: "${APP_PORT}"
    networks:
      - frontnet
  notification:
    build: ./notification
    restart: always
    environment:
      APP_PORT: "${APP_PORT}"
    networks:
      - frontnet    
  mongodb:
    container_name: mongodb
    image: mongo:6.0.2
    restart: always
    ports:
      - 27017:27017
    networks:
      - frontnet
    volumes:
      - $PWD/STORAGE/mongodb:/data/db

  redis:
    container_name: redisdb
    image: redis:latest
    restart: always
   
    ports:
      - "6379:6379"
    networks:
      - frontnet
    volumes:
      - $PWD/STORAGE/redisdb:/data


  # rabbitmq:
  #   container_name: rabbitmq
  #   image: rabbitmq:3-management-alpine
  #   hostname: rabbitmq
  #   restart: always
  #   labels:
  #     - traefik.enable=true
  #     - traefik.docker.network=frontnet
  #     - traefik.frontend.rule=Host:rab.feims.ng
  #     - traefik.port=15672
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
  #     RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
  #     APP_RABBITMQ_URL: "${APP_RABBITMQ_URL}"
  #   volumes:
  #     - ./STORAGE/rabbitmq/:/var/lib/rabbitmq/
  #     - ./STORAGE/rabbitmq/logs/:/var/log/rabbitmq
  #   networks:
  #     - frontnet

  # questdb:
  #   container_name: questdb
  #   image: questdb/questdb
  #   restart: always
  #   labels:
  #     - traefik.enable=true
  #     - traefik.frontend.auth.basic.users=admin:$$apr1$$xnY9/GY6$$wGOZhpoAxJlg008io1Wtv0
  #     - traefik.docker.network=frontnet
  #     - traefik.frontend.rule=Host:td.feims.ng
  #     - traefik.port=9000
  #   ports:
  #     - 9000:9000
  #     - 9009:9009
  #   volumes:
  #     - $PWD/STORAGE/questdb:/root
  #   networks:
  #     - frontnet

networks:
  frontnet:
